# Generated by Django 5.2.9 on 2026-01-29 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="作成日時"
            ),
        ),
    ]
