# Generated by Django 5.2.9 on 2026-02-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_article_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="body",
            field=models.TextField(blank=True, verbose_name="本文"),
        ),
    ]
