# Generated by Django 5.2.9 on 2026-01-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_article_delete_page"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="views",
            new_name="view_count",
        ),
        migrations.AddField(
            model_name="article",
            name="subtitle",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
