# Generated by Django 5.2.9 on 2026-01-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_rename_views_article_view_count_article_subtitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="subtitle",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="article",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
    ]
