# Generated by Django 5.2.9 on 2026-01-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_alter_article_subtitle_alter_article_view_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="body",
            field=models.TextField(verbose_name="本文"),
        ),
        migrations.AlterField(
            model_name="article",
            name="subtitle",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="サブタイトル"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=100, verbose_name="タイトル"),
        ),
        migrations.AlterField(
            model_name="article",
            name="view_count",
            field=models.IntegerField(default=0, verbose_name="閲覧数"),
        ),
    ]
