# Generated by Django 5.2.12 on 2026-05-05 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_article_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="author",
        ),
    ]
