# Generated by Django 5.2.9 on 2026-02-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form_lab", "0002_author_simplearticle_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="simplearticle",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
