# Generated by Django 5.2.12 on 2026-04-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form_lab", "0003_alter_author_name_alter_simplearticle_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="simplearticle",
            name="body_length",
            field=models.IntegerField(default=0),
        ),
    ]
