# Generated by Django 5.2.12 on 2026-04-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form_lab", "0004_simplearticle_body_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simplearticle",
            name="body_length",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
